// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Randy_Fanbian_P2_Ap1.Api.DAL;

#nullable disable

namespace Randy_Fanbian_P2_Ap1.Api.Migrations
{
    [DbContext(typeof(Context))]
    partial class ContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.2");

            modelBuilder.Entity("Randy_Fanbian_P2_Ap1.Models.Accesorios", b =>
                {
                    b.Property<int>("AccesorioId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("AccesorioId");

                    b.ToTable("Accesorios");

                    b.HasData(
                        new
                        {
                            AccesorioId = 1,
                            Descripcion = "Camara Tracera"
                        },
                        new
                        {
                            AccesorioId = 2,
                            Descripcion = "Pantalla interior"
                        },
                        new
                        {
                            AccesorioId = 3,
                            Descripcion = "Interior en piel"
                        },
                        new
                        {
                            AccesorioId = 4,
                            Descripcion = "Sun Roof"
                        },
                        new
                        {
                            AccesorioId = 5,
                            Descripcion = "Aros de lujo"
                        });
                });

            modelBuilder.Entity("Randy_Fanbian_P2_Ap1.Models.VehiculoDetalle", b =>
                {
                    b.Property<int>("VehiculoDetalleId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("AccesorioId")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("ValorId")
                        .HasColumnType("TEXT");

                    b.Property<int>("VehiculoId")
                        .HasColumnType("INTEGER");

                    b.HasKey("VehiculoDetalleId");

                    b.HasIndex("AccesorioId");

                    b.ToTable("VehiculoDetalle");
                });

            modelBuilder.Entity("Randy_Fanbian_P2_Ap1.Models.VehiculoDetalle", b =>
                {
                    b.HasOne("Randy_Fanbian_P2_Ap1.Models.Accesorios", null)
                        .WithMany("VehiculoDetalle")
                        .HasForeignKey("AccesorioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Randy_Fanbian_P2_Ap1.Models.Accesorios", b =>
                {
                    b.Navigation("VehiculoDetalle");
                });
#pragma warning restore 612, 618
        }
    }
}
